### ISSUE TITLE
add api for other pipelines

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/tinyify#1]
Some plugins, like factor-bundle and browserify-dynamic-import, create multiple output files. These plugins typically expose an event that you can hook into to change their [pipelines](https://npmjs.com/package/labeled-stream-splicer). It would be neat to have a simple way to add tinyify's relevant optimizations to a pipeline, maybe like this:

```js
b.on('factor.pipeline', function (file, pipeline) {
  tinyify.applyToPipeline(pipeline)
})
```

tinyify could also hardcode event handlers like that in the main plugin, to make it a bit easier to use—just add `-p tinyify` to a project that uses factor-bundle and browserify-dynamic-import and get optimizations on all outputs immediately.

**Comment by yoshuawuyts** [comment]
Yeah this sounds heaps tricky — but would be very neat if it could be figured out!
