### ISSUE TITLE
Are sourcemaps possible?

### ISSUE THREAD

**Issue by smhg** [goto-bus-stop/tinyify#6]
When using the `-d` flag on browserify, adding `tinyify` seems to be the difference between usable and unusable sourcemaps (they seem to point to the right file, but not the line) for me.
I understand you only wrap other modules, but have you been able to get working sourcemaps?

Thanks!

**Comment by goto-bus-stop** [comment]
yeah! each transform and plugin used by `tinyify` does support source maps, but some transforms may be buggy. we should fix transforms that generate incorrect source maps or that don't support input source maps.

**Comment by goto-bus-stop** [comment]
played around with it a bit, looks to me like uglifyify is losing source maps somehow. it all looks good again if i apply https://github.com/hughsk/uglifyify/pull/81

**Comment by smhg** [comment]
Awesome! Thank you!

**Comment by goto-bus-stop** [comment]
https://github.com/hughsk/uglifyify/pull/81 was merged, could you check if it works for you now after an `npm update`? thanks! 🙏

**Comment by smhg** [comment]
Tested your branch yesterday, worked perfectly (as does the regular install now).
Thanks again!

**Comment by nicolas-hili** [comment]
Hi,

I am using tinyify and I also got the aforementioned issue with the source maps. I am using browserify along with grunt-browserify. My Grunfile.js looks like the following: 

```
browserify: {
      dist: {
        files: {
          'dist/bundle.js': ['src/entry.js']
        },
        options: {
          exclude: ['fs'],
          browserifyOptions: {
            debug: true,
            standalone: 'myStandalonePackage'
          },
          transform: ['babelify'],
          plugin: [
            [
              'tinyify', {
                //debug: true,
                //sourceMap: { content: 'inline'}
              }
            ]
          ]
        }
      }
    },
```

I set `debug=true` option for browserify but it does not look like it is used by tinyify, so I tried different parameters passed to the tinyify plug-in, but nothing worked.

My config:

- grunt-browserify: 5.3.0
- tinyify: 3.0.0
- uglifyify: 5.0.0

Thanks
